#!/usr/bin/python

# debtags - Implement package tags support for Debian
#
# Copyright (C) 2003--2006  Enrico Zini <enrico@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import sys
from debian_bundle import debtags

input = sys.stdin
if len(sys.argv) > 1:
	input = open(sys.argv[1],"r")

#db = readTagDatabase(input)
#db = reverse(db)
db = debtags.readTagDatabaseReversed(input)
#dummy, db = debtags.readTagDatabaseBothWays(input)

for pkg, tags in db.items():
	# Using % here seems awkward to me, but if I use calls to
	# sys.stdout.write it becomes a bit slower
	print "%s:" % (pkg), ", ".join(tags)
