#!/usr/bin/python

# changelog_head - head like tool for .deb changelog entries
# Copyright (C) 2007 Stefano Zacchiroli <zack@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

"""Like "head" for changelog entries, return last n-th entries of the changelog
shipped in a .deb file."""

import string
import sys

from debian_bundle import debfile

if __name__ == '__main__':
    if len(sys.argv) > 3 or len(sys.argv) < 2:
        print "Usage: changelog_head DEB [ENTRIES]"
        print "  ENTRIES defaults to 10"
        sys.exit(1)

    entries = 10
    try:
        entries = int(sys.argv[2])
    except IndexError:
        pass

    deb = debfile.DebFile(sys.argv[1])
    chg = deb.changelog()
    entries = chg._blocks[:entries]
    print string.join(map(str, entries), '')

